#pragma once

#define APP_NAME "smart86-ha-panel"

#define APP_SCREEN_WIDTH 720
#define APP_SCREEN_HEIGHT 720
#define APP_CONTENT_BOX_X 0
#define APP_CONTENT_BOX_Y 60
#define APP_CONTENT_BOX_WIDTH 720
#define APP_CONTENT_BOX_HEIGHT 600
#define APP_NAV_BUTTON_COUNT 5
#define APP_LVGL_ANTIALIASING 0
#define APP_UI_REWORK_V2 1
#define APP_UI_TEST_WEATHER_ICON_OVERLAY 0

#define APP_EVENT_QUEUE_LENGTH 96
#define APP_EVENT_QUEUE_WAIT_MS 50

#define APP_LAYOUT_PATH "/littlefs/layout.json"
#define APP_LAYOUT_MAX_JSON_LEN 16384
#define APP_LAYOUT_MAX_ERRORS 16

#define APP_SETTINGS_PATH "/littlefs/settings.json"
#define APP_SETTINGS_MAX_JSON_LEN 4096

#define APP_WIFI_SSID_MAX_LEN 33
#define APP_WIFI_PASSWORD_MAX_LEN 65
#define APP_WIFI_COUNTRY_CODE_MAX_LEN 3
#define APP_HA_WS_URL_MAX_LEN 256
#define APP_HA_ACCESS_TOKEN_MAX_LEN 512
#define APP_NTP_SERVER_MAX_LEN 128
#define APP_TIME_TZ_MAX_LEN 128

#define APP_SETUP_AP_SSID_PREFIX "Smart86-Setup"
#define APP_SETUP_AP_PASSWORD ""
#define APP_SETUP_AP_CHANNEL 1
#define APP_SETUP_AP_MAX_CONNECTIONS 4

#define APP_MAX_PAGES 5
#define APP_MAX_WIDGETS_PER_PAGE 32
#define APP_MAX_WIDGETS_TOTAL (APP_MAX_PAGES * APP_MAX_WIDGETS_PER_PAGE)

#define APP_MAX_ENTITY_ID_LEN 96
#define APP_MAX_WIDGET_ID_LEN 32
#define APP_MAX_PAGE_ID_LEN 32
#define APP_MAX_STATE_LEN 64
#define APP_MAX_NAME_LEN 64
#define APP_MAX_UNIT_LEN 24
#define APP_MAX_ICON_LEN 64
#define APP_MAX_UI_OPTION_LEN 24
#define APP_MAX_COLOR_STR_LEN 16

#define APP_HA_MAX_ENTITIES 256
#define APP_HA_MAX_STATES 256
#define APP_HA_ATTRS_MAX_LEN 512

#define APP_HA_QUEUE_LENGTH 96
#define APP_HA_TASK_STACK 10240
#define APP_HA_TASK_PRIO 8

#define APP_UI_TASK_STACK 24576
#define APP_UI_TASK_PRIO 4

#define APP_LVGL_TASK_STACK 24576

#define APP_HTTP_PORT 80

#ifndef APP_HAVE_HOSTED_C6_FW_IMAGE
#define APP_HAVE_HOSTED_C6_FW_IMAGE 0
#endif

#ifdef CONFIG_APP_WIFI_SSID
#define APP_WIFI_SSID CONFIG_APP_WIFI_SSID
#else
#define APP_WIFI_SSID "YOUR_WIFI_SSID"
#endif

#ifdef CONFIG_APP_WIFI_PASSWORD
#define APP_WIFI_PASSWORD CONFIG_APP_WIFI_PASSWORD
#else
#define APP_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#endif

#ifdef CONFIG_APP_WIFI_COUNTRY_CODE
#define APP_WIFI_COUNTRY_CODE CONFIG_APP_WIFI_COUNTRY_CODE
#else
#define APP_WIFI_COUNTRY_CODE "DE"
#endif

#ifdef CONFIG_APP_WIFI_WAIT_FOR_IP
#define APP_WIFI_WAIT_FOR_IP CONFIG_APP_WIFI_WAIT_FOR_IP
#else
#define APP_WIFI_WAIT_FOR_IP 1
#endif

#ifdef CONFIG_APP_WIFI_CONNECT_TIMEOUT_MS
#define APP_WIFI_CONNECT_TIMEOUT_MS CONFIG_APP_WIFI_CONNECT_TIMEOUT_MS
#else
#define APP_WIFI_CONNECT_TIMEOUT_MS 15000
#endif

#ifdef CONFIG_APP_WIFI_MAX_RETRIES
#define APP_WIFI_MAX_RETRIES CONFIG_APP_WIFI_MAX_RETRIES
#else
#define APP_WIFI_MAX_RETRIES 8
#endif

#ifdef CONFIG_APP_WIFI_DISABLE_POWER_SAVE
#define APP_WIFI_DISABLE_POWER_SAVE CONFIG_APP_WIFI_DISABLE_POWER_SAVE
#else
#define APP_WIFI_DISABLE_POWER_SAVE 1
#endif

#ifdef CONFIG_APP_HOSTED_AUTO_UPDATE_C6_FW
#define APP_HOSTED_AUTO_UPDATE_C6_FW CONFIG_APP_HOSTED_AUTO_UPDATE_C6_FW
#else
#define APP_HOSTED_AUTO_UPDATE_C6_FW 1
#endif

#ifdef CONFIG_APP_HA_WS_URL
#define APP_HA_WS_URL CONFIG_APP_HA_WS_URL
#else
#define APP_HA_WS_URL "YOUR_HA_WS_URL"
#endif

#ifdef CONFIG_APP_HA_ACCESS_TOKEN
#define APP_HA_ACCESS_TOKEN CONFIG_APP_HA_ACCESS_TOKEN
#else
#define APP_HA_ACCESS_TOKEN "YOUR_HA_ACCESS_TOKEN"
#endif

#ifdef CONFIG_APP_HA_FETCH_INITIAL_STATES
#define APP_HA_FETCH_INITIAL_STATES CONFIG_APP_HA_FETCH_INITIAL_STATES
#else
#define APP_HA_FETCH_INITIAL_STATES 1
#endif

#ifdef CONFIG_APP_HA_SUBSCRIBE_STATE_CHANGED
#define APP_HA_SUBSCRIBE_STATE_CHANGED CONFIG_APP_HA_SUBSCRIBE_STATE_CHANGED
#else
#define APP_HA_SUBSCRIBE_STATE_CHANGED 1
#endif

#ifdef CONFIG_APP_HA_PING_INTERVAL_MS
#define APP_HA_PING_INTERVAL_MS CONFIG_APP_HA_PING_INTERVAL_MS
#else
#define APP_HA_PING_INTERVAL_MS 8000
#endif

#ifdef CONFIG_APP_NTP_SERVER
#define APP_NTP_SERVER CONFIG_APP_NTP_SERVER
#else
#define APP_NTP_SERVER "pool.ntp.org"
#endif

#ifdef CONFIG_APP_TIME_TZ
#define APP_TIME_TZ CONFIG_APP_TIME_TZ
#else
#define APP_TIME_TZ "CET-1CEST,M3.5.0/2,M10.5.0/3"
#endif
