#include "ui/fonts/mdi_font_registry.h"

#ifndef APP_HAVE_MDI_ICON_FONT
#define APP_HAVE_MDI_ICON_FONT 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT
#define APP_HAVE_MDI_TOP50_FONT 0
#endif

#ifndef APP_HAVE_MDI_STANDARD_FONT
#define APP_HAVE_MDI_STANDARD_FONT 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT_72
#define APP_HAVE_MDI_TOP50_FONT_72 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT_56
#define APP_HAVE_MDI_TOP50_FONT_56 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT_42
#define APP_HAVE_MDI_TOP50_FONT_42 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT_LEGACY
#define APP_HAVE_MDI_TOP50_FONT_LEGACY 0
#endif

#ifndef APP_HAVE_MDI_WEATHER_FONT_100
#define APP_HAVE_MDI_WEATHER_FONT_100 0
#endif

#ifndef APP_HAVE_MDI_WEATHER_FONT_120
#define APP_HAVE_MDI_WEATHER_FONT_120 0
#endif

#ifndef APP_HAVE_MDI_WEATHER_FONT_20
#define APP_HAVE_MDI_WEATHER_FONT_20 0
#endif

#if APP_HAVE_MDI_ICON_FONT
/* Generated by LVGL Font Converter (name must match the converter setting). */
#if APP_HAVE_MDI_TOP50_FONT
#if APP_HAVE_MDI_TOP50_FONT_56
LV_FONT_DECLARE(mditop50icons56);
#endif
#if APP_HAVE_MDI_TOP50_FONT_42
LV_FONT_DECLARE(mditop50icons42);
#endif
#if APP_HAVE_MDI_TOP50_FONT_72
LV_FONT_DECLARE(mditop50icons72);
#endif
#if APP_HAVE_MDI_TOP50_FONT_LEGACY
LV_FONT_DECLARE(mditop50icons);
#endif
#elif APP_HAVE_MDI_STANDARD_FONT
LV_FONT_DECLARE(mdi_standard_icons_56);
#endif
#endif

#if APP_HAVE_MDI_WEATHER_FONT_100
LV_FONT_DECLARE(mdiweatherIcons100);
#endif

#if APP_HAVE_MDI_WEATHER_FONT_120
LV_FONT_DECLARE(mdiweatherIcons120);
#endif

#if APP_HAVE_MDI_WEATHER_FONT_20
LV_FONT_DECLARE(mdiweatherIcons20);
#endif

const lv_font_t *mdi_font_large(void)
{
#if APP_HAVE_MDI_ICON_FONT
#if APP_HAVE_MDI_TOP50_FONT
#if APP_HAVE_MDI_TOP50_FONT_56
    return &mditop50icons56;
#elif APP_HAVE_MDI_TOP50_FONT_72
    return &mditop50icons72;
#elif APP_HAVE_MDI_TOP50_FONT_LEGACY
    return &mditop50icons;
#else
    return NULL;
#endif
#elif APP_HAVE_MDI_STANDARD_FONT
    return &mdi_standard_icons_56;
#else
    return NULL;
#endif
#else
    return NULL;
#endif
}

bool mdi_font_large_available(void)
{
    return mdi_font_large() != NULL;
}

const lv_font_t *mdi_font_weather_100(void)
{
#if APP_HAVE_MDI_WEATHER_FONT_100
    return &mdiweatherIcons100;
#else
    return NULL;
#endif
}

bool mdi_font_weather_100_available(void)
{
    return mdi_font_weather_100() != NULL;
}

const lv_font_t *mdi_font_weather_120(void)
{
#if APP_HAVE_MDI_WEATHER_FONT_120
    return &mdiweatherIcons120;
#else
    return NULL;
#endif
}

bool mdi_font_weather_120_available(void)
{
    return mdi_font_weather_120() != NULL;
}

const lv_font_t *mdi_font_weather_20(void)
{
#if APP_HAVE_MDI_WEATHER_FONT_20
    return &mdiweatherIcons20;
#else
    return NULL;
#endif
}

bool mdi_font_weather_20_available(void)
{
    return mdi_font_weather_20() != NULL;
}

const lv_font_t *mdi_font_weather_small(void)
{
#if APP_HAVE_MDI_WEATHER_FONT_20
    return &mdiweatherIcons20;
#endif
#if APP_HAVE_MDI_ICON_FONT && APP_HAVE_MDI_TOP50_FONT
#if APP_HAVE_MDI_TOP50_FONT_42
    return &mditop50icons42;
#elif APP_HAVE_MDI_TOP50_FONT_56
    return &mditop50icons56;
#elif APP_HAVE_MDI_TOP50_FONT_72
    return &mditop50icons72;
#else
    return mdi_font_large();
#endif
#else
    return mdi_font_large();
#endif
}

bool mdi_font_weather_small_available(void)
{
    return mdi_font_weather_small() != NULL;
}

const lv_font_t *mdi_font_weather(void)
{
#if APP_HAVE_MDI_ICON_FONT && APP_HAVE_MDI_TOP50_FONT && APP_HAVE_MDI_TOP50_FONT_72
    return &mditop50icons72;
#else
    return mdi_font_large();
#endif
}

bool mdi_font_weather_available(void)
{
    return mdi_font_weather() != NULL;
}
