#pragma once

#include <stdbool.h>

#include "lvgl.h"
#include "app_config.h"

#ifndef APP_UI_REWORK_V2
#define APP_UI_REWORK_V2 1
#endif

/*
 * Global switch for experimental tile spacing/alignment tuning.
 * Set to 0 to instantly restore legacy per-tile layout positions.
 */
#ifndef APP_UI_TILE_LAYOUT_TUNED
#define APP_UI_TILE_LAYOUT_TUNED 1
#endif

#if APP_UI_REWORK_V2

#ifndef APP_UI_CARD_RADIUS
#define APP_UI_CARD_RADIUS 22
#endif

#define APP_UI_COLOR_SCREEN_BG 0x070B12
#define APP_UI_COLOR_SCREEN_BG_GRAD 0x0F1A28
#define APP_UI_COLOR_CONTENT_BG 0x18232F
#define APP_UI_COLOR_CONTENT_BORDER 0x2A3A4C

#define APP_UI_COLOR_TOPBAR_TEXT 0xEAF2FA
#define APP_UI_COLOR_TOPBAR_MUTED 0xA1B1C1
#define APP_UI_COLOR_TOPBAR_STATUS_ON 0xC7D1DB
#define APP_UI_COLOR_TOPBAR_STATUS_OFF 0x5F6B78
#define APP_UI_COLOR_TOPBAR_BG 0x0D1723
#define APP_UI_COLOR_TOPBAR_BORDER 0x2A3D50
#define APP_UI_COLOR_TOPBAR_CHIP_BG 0x1B2A3A
#define APP_UI_COLOR_TOPBAR_CHIP_BORDER 0x385064

#define APP_UI_COLOR_TEXT_PRIMARY 0xF5F9FD
#define APP_UI_COLOR_TEXT_MUTED 0x9FB2C4
#define APP_UI_COLOR_TEXT_SOFT 0xB7C3D0

#define APP_UI_COLOR_NAV_BG 0x152B38
#define APP_UI_COLOR_NAV_BORDER 0x4D93B3
#define APP_UI_COLOR_NAV_BTN_BG_IDLE 0x2A4454
#define APP_UI_COLOR_NAV_BTN_BG_ACTIVE 0x365F74
#define APP_UI_COLOR_NAV_TAB_IDLE 0xA9C3D0
#define APP_UI_COLOR_NAV_TAB_ACTIVE 0x6FE8FF
#define APP_UI_COLOR_NAV_HOME_IDLE 0x9EB8C7
#define APP_UI_COLOR_NAV_HOME_ACTIVE 0x53E5FF

#define APP_UI_COLOR_OK 0x59D87C
#define APP_UI_COLOR_ERROR 0xE97474
#define APP_UI_COLOR_WIFI_OFF 0x6D7E90

#define APP_UI_COLOR_CARD_BG_OFF 0x1D2935
#define APP_UI_COLOR_CARD_BG_ON 0x223344
#define APP_UI_COLOR_CARD_BORDER 0x314456
#define APP_UI_COLOR_CARD_ICON_OFF 0x8EA1B4
#define APP_UI_COLOR_CARD_ICON_ON 0x53E5FF
#define APP_UI_COLOR_STATE_ON 0xD6EAF8
#define APP_UI_COLOR_STATE_OFF 0xA2B2C3

#define APP_UI_COLOR_LIGHT_ICON_ON 0xFFCF6B
#define APP_UI_COLOR_LIGHT_TRACK_ON 0x5A4722
#define APP_UI_COLOR_LIGHT_TRACK_OFF 0x435262
#define APP_UI_COLOR_LIGHT_IND_ON 0xFFC34D
#define APP_UI_COLOR_LIGHT_IND_OFF 0x7E93A5
#define APP_UI_COLOR_LIGHT_KNOB_ON 0xFFE2A3
#define APP_UI_COLOR_LIGHT_KNOB_OFF 0xB0BFD0

#define APP_UI_COLOR_HEAT_ICON_ON 0xFF9A72
#define APP_UI_COLOR_HEAT_TRACK_ON 0x5C2C20
#define APP_UI_COLOR_HEAT_TRACK_OFF 0x414F5D
#define APP_UI_COLOR_HEAT_IND_ON 0xFF7340
#define APP_UI_COLOR_HEAT_IND_OFF 0x9BB0C1
#define APP_UI_COLOR_HEAT_KNOB_ON 0xFF916A
#define APP_UI_COLOR_HEAT_KNOB_OFF 0xC2CED9

#define APP_UI_COLOR_WEATHER_ICON 0xEAF3FB

#else

#ifndef APP_UI_CARD_RADIUS
#define APP_UI_CARD_RADIUS 20
#endif

#define APP_UI_COLOR_SCREEN_BG 0x0B1018
#define APP_UI_COLOR_SCREEN_BG_GRAD 0x142433
#define APP_UI_COLOR_CONTENT_BG 0x545454
#define APP_UI_COLOR_CONTENT_BORDER 0x545454

#define APP_UI_COLOR_TOPBAR_TEXT 0xFFFFFF
#define APP_UI_COLOR_TOPBAR_MUTED 0xAFC2D3
#define APP_UI_COLOR_TOPBAR_STATUS_ON 0xD3DAE1
#define APP_UI_COLOR_TOPBAR_STATUS_OFF 0x69737D
#define APP_UI_COLOR_TOPBAR_BG 0x1A2631
#define APP_UI_COLOR_TOPBAR_BORDER 0x3B5668
#define APP_UI_COLOR_TOPBAR_CHIP_BG 0x2A3A46
#define APP_UI_COLOR_TOPBAR_CHIP_BORDER 0x4D6678

#define APP_UI_COLOR_TEXT_PRIMARY 0xF5F7FA
#define APP_UI_COLOR_TEXT_MUTED 0xAFC2D3
#define APP_UI_COLOR_TEXT_SOFT 0xD0D0D0

#define APP_UI_COLOR_NAV_BG 0x1C2933
#define APP_UI_COLOR_NAV_BORDER 0x4A88A6
#define APP_UI_COLOR_NAV_BTN_BG_IDLE 0x32424E
#define APP_UI_COLOR_NAV_BTN_BG_ACTIVE 0x426073
#define APP_UI_COLOR_NAV_TAB_IDLE 0xB7C8D1
#define APP_UI_COLOR_NAV_TAB_ACTIVE 0x66E6FF
#define APP_UI_COLOR_NAV_HOME_IDLE 0xAFC1CA
#define APP_UI_COLOR_NAV_HOME_ACTIVE 0x38F2FF

#define APP_UI_COLOR_OK 0x57D56C
#define APP_UI_COLOR_ERROR 0xD05C5C
#define APP_UI_COLOR_WIFI_OFF 0x7A7A7A

#define APP_UI_COLOR_CARD_BG_OFF 0x262626
#define APP_UI_COLOR_CARD_BG_ON 0x292929
#define APP_UI_COLOR_CARD_BORDER 0x262626
#define APP_UI_COLOR_CARD_ICON_OFF 0x909090
#define APP_UI_COLOR_CARD_ICON_ON 0x53E5FF
#define APP_UI_COLOR_STATE_ON 0xFFE08A
#define APP_UI_COLOR_STATE_OFF 0xB4B4B4

#define APP_UI_COLOR_LIGHT_ICON_ON 0xFFC200
#define APP_UI_COLOR_LIGHT_TRACK_ON 0x4D3A00
#define APP_UI_COLOR_LIGHT_TRACK_OFF 0x474747
#define APP_UI_COLOR_LIGHT_IND_ON 0xFFC200
#define APP_UI_COLOR_LIGHT_IND_OFF 0x7F7F7F
#define APP_UI_COLOR_LIGHT_KNOB_ON 0xF9C100
#define APP_UI_COLOR_LIGHT_KNOB_OFF 0xB3B3B3

#define APP_UI_COLOR_HEAT_ICON_ON 0xFF8A63
#define APP_UI_COLOR_HEAT_TRACK_ON 0x5D2311
#define APP_UI_COLOR_HEAT_TRACK_OFF 0x414441
#define APP_UI_COLOR_HEAT_IND_ON 0xFF5D29
#define APP_UI_COLOR_HEAT_IND_OFF 0xB4B2B4
#define APP_UI_COLOR_HEAT_KNOB_ON 0xFF5F2C
#define APP_UI_COLOR_HEAT_KNOB_OFF 0xB4B2B4

#define APP_UI_COLOR_WEATHER_ICON 0xE9EFF6

#endif

void theme_default_init(void);
void theme_default_style_screen(lv_obj_t *obj);
void theme_default_style_card(lv_obj_t *obj);
void theme_default_style_button(lv_obj_t *obj, bool is_on);
lv_color_t theme_default_color_text_primary(void);
lv_color_t theme_default_color_text_muted(void);
